/**
 * @jest-environment jsdom
*/

import { getReportWriter } from './ReportWriter';
import { ScenarioAggregator } from '../ScenarioAggregator';

/**
 * This is a very loose integration test which really only tests the happy path and verifies that the logic
 * runs to completion. It doesn't perform any deep assertions on the output.
 */
test('getReport should return a document fragment', () => {
    document.body.innerHTML = getTemplateHtml();

    const scenarioAggregator = new ScenarioAggregator(getTestData().Performances);
    const scenariosByFeature = scenarioAggregator.getScenariosByFeature();
    const reportWriter = getReportWriter();
    
    const result = reportWriter.getReport(scenariosByFeature);
    expect(result).not.toBeNull();
});


const testData = {
    "Metadata": {
        "Timestamp": "2024-10-29T21:46:29.4707208Z",
        "ReportFormatVersion": "2.0.0"
    },
    "Performances": [
        {
            "NamingHierarchy": [
                {
                    "Identifier": "6077245f-9245-4021-adab-cedf66d414fb",
                    "Name": "Adding up numbers",
                    "WasIdentifierAutoGenerated": true
                },
                {
                    "Identifier": "0b2bd6e4-4b73-4d92-a451-7b8dbcabb9e7",
                    "Name": "Mathias should be able to add three numbers in a single step",
                    "WasIdentifierAutoGenerated": true
                }
            ],
            "Outcome": "Success",
            "Reportables": [
                {
                    "Type": "ActorCreatedReport",
                    "Report": "Mathias joined the performance",
                    "ActorName": "Mathias"
                },
                {
                    "Type": "ActorGainedAbilityReport",
                    "Report": "Mathias is able to add numbers to a running total",
                    "ActorName": "Mathias"
                },
                {
                    "Type": "ActorSpotlitReport",
                    "Report": "Mathias was put into the spotlight",
                    "ActorName": "Mathias"
                },
                {
                    "Type": "PerformableReport",
                    "PerformableType": "CSF.Screenplay.AddingUp.SetTheNumber",
                    "PerformancePhase": "Given",
                    "Result": null,
                    "HasResult": false,
                    "Exception": null,
                    "ExceptionIsFromConsumedPerformable": false,
                    "Assets": [
                        {
                            "FilePath": "abc.txt",
                            "FileSummary": "A text file"
                        },
                        {
                            "FilePath": "one.png",
                            "FileSummary": "A picture"
                        }
                    ],
                    "Reportables": [],
                    "Report": "Mathias sets the running total to 50",
                    "ActorName": "Mathias"
                },
                {
                    "Type": "PerformableReport",
                    "PerformableType": "CSF.Screenplay.AddingUp.AddThreeNumbers",
                    "PerformancePhase": "When",
                    "Result": null,
                    "HasResult": false,
                    "Exception": null,
                    "ExceptionIsFromConsumedPerformable": false,
                    "Assets": [],
                    "Reportables": [
                        {
                            "Type": "PerformableReport",
                            "PerformableType": "CSF.Screenplay.AddingUp.AddTheNumber",
                            "PerformancePhase": "",
                            "Result": null,
                            "HasResult": false,
                            "Exception": null,
                            "ExceptionIsFromConsumedPerformable": false,
                            "Assets": [],
                            "Reportables": [],
                            "Report": "Mathias adds 40 to the running total",
                            "ActorName": "Mathias"
                        },
                        {
                            "Type": "PerformableReport",
                            "PerformableType": "CSF.Screenplay.AddingUp.AddTheNumber",
                            "PerformancePhase": "",
                            "Result": null,
                            "HasResult": false,
                            "Exception": null,
                            "ExceptionIsFromConsumedPerformable": false,
                            "Assets": [],
                            "Reportables": [],
                            "Report": "Mathias adds 30 to the running total",
                            "ActorName": "Mathias"
                        },
                        {
                            "Type": "PerformableReport",
                            "PerformableType": "CSF.Screenplay.AddingUp.AddTheNumber",
                            "PerformancePhase": "",
                            "Result": null,
                            "HasResult": false,
                            "Exception": null,
                            "ExceptionIsFromConsumedPerformable": false,
                            "Assets": [],
                            "Reportables": [],
                            "Report": "Mathias adds 20 to the running total",
                            "ActorName": "Mathias"
                        }
                    ],
                    "Report": "Mathias adds three numbers to the running total: 40, 30 \u0026 20",
                    "ActorName": "Mathias"
                },
                {
                    "Type": "PerformableReport",
                    "PerformableType": "CSF.Screenplay.AddingUp.GetTheNumber",
                    "PerformancePhase": "Then",
                    "Result": "140",
                    "HasResult": true,
                    "Exception": null,
                    "ExceptionIsFromConsumedPerformable": false,
                    "Assets": [],
                    "Reportables": [],
                    "Report": "Mathias gets the running total",
                    "ActorName": "Mathias"
                }
            ]
        },
        {
            "NamingHierarchy": [
                {
                    "Identifier": "6077245f-9245-4021-adab-cedf66d414fb",
                    "Name": "Adding up numbers",
                    "WasIdentifierAutoGenerated": true
                },
                {
                    "Identifier": "8c3e2e1a-f141-4484-a7a9-ac84772eefa5",
                    "Name": "Mathias should be able to add three numbers together and get the correct result",
                    "WasIdentifierAutoGenerated": true
                }
            ],
            "Outcome": "Success",
            "Reportables": [
                {
                    "Type": "ActorCreatedReport",
                    "Report": "Mathias joined the performance",
                    "ActorName": "Mathias"
                },
                {
                    "Type": "ActorGainedAbilityReport",
                    "Report": "Mathias is able to add numbers to a running total",
                    "ActorName": "Mathias"
                },
                {
                    "Type": "ActorSpotlitReport",
                    "Report": "Mathias was put into the spotlight",
                    "ActorName": "Mathias"
                },
                {
                    "Type": "PerformableReport",
                    "PerformableType": "CSF.Screenplay.AddingUp.SetTheNumber",
                    "PerformancePhase": "Given",
                    "Result": null,
                    "HasResult": false,
                    "Exception": null,
                    "ExceptionIsFromConsumedPerformable": false,
                    "Assets": [],
                    "Reportables": [],
                    "Report": "Mathias sets the running total to 50",
                    "ActorName": "Mathias"
                },
                {
                    "Type": "PerformableReport",
                    "PerformableType": "CSF.Screenplay.AddingUp.AddTheNumber",
                    "PerformancePhase": "When",
                    "Result": null,
                    "HasResult": false,
                    "Exception": null,
                    "ExceptionIsFromConsumedPerformable": false,
                    "Assets": [],
                    "Reportables": [],
                    "Report": "Mathias adds 70 to the running total",
                    "ActorName": "Mathias"
                },
                {
                    "Type": "PerformableReport",
                    "PerformableType": "CSF.Screenplay.AddingUp.AddTheNumber",
                    "PerformancePhase": "When",
                    "Result": null,
                    "HasResult": false,
                    "Exception": null,
                    "ExceptionIsFromConsumedPerformable": false,
                    "Assets": [],
                    "Reportables": [],
                    "Report": "Mathias adds 20 to the running total",
                    "ActorName": "Mathias"
                },
                {
                    "Type": "PerformableReport",
                    "PerformableType": "CSF.Screenplay.AddingUp.GetTheNumber",
                    "PerformancePhase": "Then",
                    "Result": "140",
                    "HasResult": true,
                    "Exception": null,
                    "ExceptionIsFromConsumedPerformable": false,
                    "Assets": [],
                    "Reportables": [],
                    "Report": "Mathias gets the running total",
                    "ActorName": "Mathias"
                }
            ]
        },
        {
            "NamingHierarchy": [
                {
                    "Identifier": "6077245f-9245-4021-adab-cedf66d414fb",
                    "Name": "Adding up numbers",
                    "WasIdentifierAutoGenerated": true
                },
                {
                    "Identifier": "b6410a9a-b524-40a6-9332-19e3c69d0357",
                    "Name": "Mathias should be able to add two numbers together and get the correct result",
                    "WasIdentifierAutoGenerated": true
                }
            ],
            "Outcome": "Success",
            "Reportables": [
                {
                    "Type": "ActorCreatedReport",
                    "Report": "Mathias joined the performance",
                    "ActorName": "Mathias"
                },
                {
                    "Type": "ActorGainedAbilityReport",
                    "Report": "Mathias is able to add numbers to a running total",
                    "ActorName": "Mathias"
                },
                {
                    "Type": "ActorSpotlitReport",
                    "Report": "Mathias was put into the spotlight",
                    "ActorName": "Mathias"
                },
                {
                    "Type": "PerformableReport",
                    "PerformableType": "CSF.Screenplay.AddingUp.SetTheNumber",
                    "PerformancePhase": "Given",
                    "Result": null,
                    "HasResult": false,
                    "Exception": null,
                    "ExceptionIsFromConsumedPerformable": false,
                    "Assets": [],
                    "Reportables": [],
                    "Report": "Mathias sets the running total to 50",
                    "ActorName": "Mathias"
                },
                {
                    "Type": "PerformableReport",
                    "PerformableType": "CSF.Screenplay.AddingUp.AddTheNumber",
                    "PerformancePhase": "When",
                    "Result": null,
                    "HasResult": false,
                    "Exception": null,
                    "ExceptionIsFromConsumedPerformable": false,
                    "Assets": [],
                    "Reportables": [],
                    "Report": "Mathias adds 70 to the running total",
                    "ActorName": "Mathias"
                },
                {
                    "Type": "PerformableReport",
                    "PerformableType": "CSF.Screenplay.AddingUp.GetTheNumber",
                    "PerformancePhase": "Then",
                    "Result": "120",
                    "HasResult": true,
                    "Exception": null,
                    "ExceptionIsFromConsumedPerformable": false,
                    "Assets": [],
                    "Reportables": [],
                    "Report": "Mathias gets the running total",
                    "ActorName": "Mathias"
                }
            ]
        }
    ]
};

function getTestData() {
    return testData;
}

const templateHtml = `<template id="featureTemplate">
<li class="collapsed">
    <span class="featureIdentifier" title="Feature identifier">Feature Identifier</span>
    <h3 class="featureName" title="Feature name; click to expand/collapse">Feature name</h3>
    <ul class="scenarioList collapsible"></ul>
</li>
</template>
<template id="scenarioTemplate">
<li class="collapsed">
    <span class="scenarioIdentifier" title="Scenario identifier">Scenario Identifier</span>
    <h4 class="scenarioName" title="Scenario name; click to expand/collapse">Scenario name</h4>
    <ol class="reportableList collapsible"></ol>
</li>
</template>
<template id="reportableTemplate">
<li class="collapsed">
    <span class="type"><i>Reportable type name</i></span><span class="phase">Given</span><span class="report">Report text</span>
    <div class="result">Result</div>
    <code class="exception">Exception</code>
    <aside>
        <span class="performableType"><i>Performable .NET type name</i></span>
        <div class="assets" title="Assets produced from this performable"><ul></ul></div>
    </aside>
    <ol class="reportableList collapsible"></ol>
</li>
</template>
<template id="assetTemplate">
<li><a href="Asset path" class="image" title="Download/view this asset">Asset summary</a></li>
</template>`;

function getTemplateHtml() {
    return templateHtml;
}
