// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSF.Screenplay.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionFormats {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionFormats() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ExceptionFormats", typeof(ExceptionFormats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AbilityMustImplementType {
            get {
                return ResourceManager.GetString("AbilityMustImplementType", resourceCulture);
            }
        }
        
        internal static string ActorIsMissingAnAbility {
            get {
                return ResourceManager.GetString("ActorIsMissingAnAbility", resourceCulture);
            }
        }
        
        internal static string ActorMustHaveAScenarioId {
            get {
                return ResourceManager.GetString("ActorMustHaveAScenarioId", resourceCulture);
            }
        }
        
        internal static string ActorMustHaveAName {
            get {
                return ResourceManager.GetString("ActorMustHaveAName", resourceCulture);
            }
        }
        
        internal static string DuplicateActorsNotAllowedInCast {
            get {
                return ResourceManager.GetString("DuplicateActorsNotAllowedInCast", resourceCulture);
            }
        }
        
        internal static string IntegrationConfigTypeMustImplementCorrectInterface {
            get {
                return ResourceManager.GetString("IntegrationConfigTypeMustImplementCorrectInterface", resourceCulture);
            }
        }
        
        internal static string MustBeAnActorInTheSpotlight {
            get {
                return ResourceManager.GetString("MustBeAnActorInTheSpotlight", resourceCulture);
            }
        }
    }
}
