name: 'Setup test dependencies'
description: 'Installs and configures additional dependencies to thoroughly test CSF.Screenplay'
inputs:
  java-version:
    description: 'The version of Java to install'
    default: 21
  java-dist:
    description: 'The distribution of Java to install'
    default: 'zulu'
  x-display:
    description: 'The XServer display to configure for web browsers'
    default: ':99'
  x-resolution:
    description: 'The XServer screen resolution `widthxheight` for web browsers'
    default: '1280x1024'

runs:
  using: 'composite'
  steps:
    # Installation
    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Install Coverlet console
      run: dotnet tool install --global coverlet.console
    - name: Install Java JDK for SonarScanner
      uses: actions/setup-java@v5.1.0
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-dist }}
    
    # Prepare to run Chrome
    # See https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
    - name: Disable AppArmor restrictions so Chrome may run
      run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
    - name: Start an Xvfb display so Chrome may run
      run: Xvfb -ac ${{ inputs.x-display }} -screen 0 ${{ inputs.x-resolution }}x16 &
    
    # Prime Selenium manager with initial config
    - name: Setup Selenium Manager config
      run: |
        mkdir ~/.cache/selenium
        cp Tools/se-config.toml ~/.cache/selenium

