name: 'Checkout CSF.Screenplay'
description: 'Checks out the repository using standard options'
inputs:
  fetch-depth:
    description: 'The checkout fetch depth'
    default: 0
  
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        lfs: true