name: Update docs website

on:
  workflow_run:
    workflows: [.NET CI]
    types: [completed]
    branches: [master]

jobs:

  build_and_commit:
    name: Build & commit docs website
    runs-on: ubuntu-slim
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: ./.github/actions/standard-checkout
      - uses: ./.github/actions/setup-build-dependencies
      - uses: ./.github/actions/restore-dependencies
      - name: Remove old docs
        run: dotnet clean CSF.Screenplay.Docs
      - name: Build new docs
        run: dotnet build -c Docs CSF.Screenplay.Docs
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: -A docs/
          default_author: github_actor
          committer_name: Github Actions Workflow (bot)
          committer_email: github-actions-workflow@bots.noreply.github.com
          fetch: true
          message: Publish updated documentation website
          push: origin master
    

